### ISSUE TITLE
Use a newer version of marked.js

### ISSUE THREAD

**Issue by ondras** [evancz/elm-markdown#16]
The bundled marked.js is apparently somewhat old, as it does not support the "three dashes smartypants" replacement. It would be nice to update the library to its latest version.

Upstream: https://github.com/chjj/marked/blame/master/lib/marked.js#L719

**Comment by liamcurry** [comment]
Bumping this since [a new XSS exploit was just found](https://snyk.io/blog/marked-xss-vulnerability/) in the marked lib. 

It looks like marked is no longer maintained, so to fix this, [this PR/patch will have to be applied](https://github.com/chjj/marked/pull/592).

Maybe it's time to use a new Markdown library?

**Comment by tekul** [comment]
Seems like [another similar issue with marked](https://snyk.io/vuln/npm:marked:20170112) was reported last month. It would be good to at least update to the current version in the meantime, since these specific issues do seem to have been fixed.
